### PR TITLE
aave draft

### PR DESCRIPTION
**Pull request by alcueca**

### CODE REVIEW

**Comment by ultrasecreth** [comment]
I think you're better off encoding/decoding a struct instead of a tuple.

Also that struct should work for all wrappers, so it can be extracted to its own file with it's own global functions, making the overall code nicer :)

**Comment by ultrasecreth** [comment]
Build should pass now, but needs formatting first

**Comment by alcueca** [comment]
Thanks for fixing that. What struct do you refer to, something that would replace `(msg.sender, loanReceiver, callback.encodeFunction(), initiatorData)`. If that is what you mean I don't think it would work, because that list of parameters is different for each wrapper.

**Comment by ultrasecreth** [comment]
> Thanks for fixing that. What struct do you refer to, something that would replace `(msg.sender, loanReceiver, callback.encodeFunction(), initiatorData)`. If that is what you mean I don't think it would work, because that list of parameters is different for each wrapper.
> 
> 

Yeah, I saw that, but I think a struct per wrapper is still better :)

**Pull request merged**
